firstbackend/firstbackend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tweet/', include('tweet.urls', namespace='tweet')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

firstbackend/tweet/urls.py
from django.urls import path
from . import views

app_name = 'tweet'  

urlpatterns = [
    path('', views.tweet_list, name='tweet_list'),
    path('create/', views.tweet_create, name='tweet_create'),
    path('edit/<int:tweet_id>/', views.tweet_edit, name='tweet_edit'),
    path('delete/<int:tweet_id>/', views.tweet_delete, name='tweet_delete'),
    path('register/', views.register, name='register'),
]

firstbackend/tweet/models.py
from django.db import models
from django.contrib.auth.models import User


class Tweet(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    photo = models.ImageField(upload_to="tweets/photos/", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

def __str__(self):
    return f"{self.user.username}: {self.content[:20]}..."

firstbackend/tweet/forms.py
from django import forms
from .models import Tweet
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class TweetForm(forms.ModelForm):
    class Meta:
        model = Tweet
        fields = ['content', 'photo']

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

firstbackend/tweet/views.py
from django.shortcuts import redirect, render
from .models import Tweet
from .forms import TweetForm
from .forms import UserRegistrationForm
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
# Create your views here.

def index(request):
    return render(request, "index.html")

def tweet_list(request):
    tweets = Tweet.objects.all().order_by("-created_at")
    return render(request, "tweet_list.html", {"tweets": tweets})

@login_required
def tweet_create(request):
    if request.method == "POST":
        form = TweetForm(request.POST, request.FILES)
        if form.is_valid():
            tweet = form.save(commit=False)
            tweet.user = request.user
            tweet.save()
            return redirect("tweet:tweet_list")
    else:
        form = TweetForm()
    return render(request, "tweet_form.html", {"form": form})

@login_required
def tweet_edit(request, tweet_id):
    tweet = get_object_or_404(Tweet, id=tweet_id)
    if request.method == "POST":
        form = TweetForm(request.POST, request.FILES, instance=tweet)
        if form.is_valid():
            form.save()
            return redirect("tweet:tweet_list")
    else:
        form = TweetForm(instance=tweet)
    return render(request, "tweet_form.html", {"form": form})

@login_required
def tweet_delete(request, tweet_id):
    tweet = get_object_or_404(Tweet, id=tweet_id)
    if request.method == "POST":
        tweet.delete()
        return redirect("tweet:tweet_list")
    return render(request, "tweet_confirm_delete.html", {"tweet": tweet})


def register(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data["password1"])
            user.save()
            login(request, user)
            return redirect("tweet:tweet_list")

    else:
        form = UserRegistrationForm()
    return render(request, "registration/register.html", {"form": form})

firstbackend/tweet/templates/index.html
{% extends "layout.html" %}

{% block content %}
    <h1 class="text-white">Welcome to My Tweet</h1>
    <p class="text-white">This is a simple tweet application.</p>
{% endblock %}

firstbackend/tweet/templates/layout.html
{%load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %} 
            My tweet
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="bg-dark">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">TweetBar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      <a href="{% url 'tweet:tweet_list' %}" class="btn btn-primary">Tweet Home</a>
      {%if user.is_authenticated %}
        <form method="post" action="{% url 'logout' %}">
          {% csrf_token %}
          <button class="btn btn-danger" type="submit">Logout</button>
        </form>
      {%else%}
      <a href="{% url 'tweet:register' %}" class="btn btn-primary">Register</a>
      <a href="{% url 'login' %}" class="btn btn-primary">Login</a>
      {%endif%}
    </div>
  </div>
</nav>
    <div class="container">
        {% block content %}
        <div class="bg-light p-5 rounded">
            <h1>Welcome to My Tweet</h1>
            <p>This is a simple tweet application.</p>
        </div>
        {% endblock %}
    
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

firstbackend/tweet/templates/tweet_confirm_delete.html
{% extends "layout.html" %}

{% block content %}
    <h1 class="text-white">Are you sure you want to delete, this action can't be undone</h1>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Confirm Delete</button>
    </form>
    <a href="{% url 'tweet:tweet_list' %}" class="btn btn-secondary">Cancel</a>
{% endblock %}

firstbackend/tweet/templates/tweet_form.html
{% extends "layout.html" %}

{% block content %}
    <h1 class="text-white">Welcome to My Tweet</h1>
    <p class="text-white">This is a simple tweet application.</p>
    <h2>{% if form.instance.pk %}
        Edit Tweet
        {% else %}
        Create Tweet
        {% endif %}</h2>
        <form method="post" enctype="multipart/form-data" class="form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        <a href="{% url 'tweet:tweet_list' %}" class="btn btn-secondary">Cancel</a>
{% endblock %}

firstbackend/tweet/templates/tweet_list.html
{% extends "layout.html" %}

{% block content %}
    <h1 class="text-white">Welcome to My Tweet</h1>
    <p class="text-white">This is a simple tweet application.</p>

    <a class="btn btn-primary" href="{% url 'tweet:tweet_create' %}">Create Tweet</a>
    <div class="container row gap-3">
        {% for tweet in tweets %}
        <div class="card" style="width: 18rem;">
            {% if tweet.photo %}
            <img src="{{ tweet.photo.url }}" class="card-img-top" alt="...">
            {% endif %}
            <div class="card-body">
                <h5 class="card-title">{{ tweet.user.username }}</h5>
                <p class="card-text">{{ tweet.content }}</p>
                {% if tweet.user == request.user %}
                    <a href="{% url 'tweet:tweet_edit' tweet.id %}" class="btn btn-primary">Edit</a>
                    <a href="{% url 'tweet:tweet_delete' tweet.id %}" class="btn btn-danger">Delete</a>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}